services:
    example-nginx:
        build:
            context: .
            dockerfile: Dockerfile_Laravel
        ports:
            - 9000:9000
        volumes:
            - example-volume:/var/www/html/storage
        networks:
            - example-network


    nginx:
        build:
            context: .
            dockerfile: Dockerfile_Nginx
        ports:
            - 80:80
        networks:
            - example-network

    mysql:
        image: 'mysql:latest'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'example-mysql:/var/lib/mysql'
        networks:
            - example-network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

networks:
    example-network:
        driver: bridge
volumes:
    example-volume:
        driver: local
    example-mysql:
        driver: local
